version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  api:
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOSTNAME=mysql
      - PORT=3001
    volumes:
      - ./:/app
    user: node
    working_dir: /app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql